app_job:
    path:     /
    defaults: { _controller: "JoboardBundle:Job:index" }

app_job_show:
    pattern:  /{company}/{location}/{id}/{position}
    defaults: { _controller: "JoboardBundle:Job:show" }
    requirements:
        id:  \d+
app_job_new:
    path:     /new
    defaults: { _controller: "JoboardBundle:Job:new" }

app_job_create:
    path:     /create
    defaults: { _controller: "JoboardBundle:Job:create" }
    requirements: { _method: post }

app_job_edit:
    path:     /{id}/edit
    defaults: { _controller: "JoboardBundle:Job:edit" }

app_job_update:
    path:     /{id}/update
    defaults: { _controller: "JoboardBundle:Job:update" }
    requirements: { _method: post|put }

app_job_delete:
    path:     /{id}/delete
    defaults: { _controller: "JoboardBundle:Job:delete" }
    requirements: { _method: post|delete }

app_job_extend:
   pattern:  /{token}/extend/
   defaults: { _controller: "AppJoboardBundle:Job:extend" }
   requirements: { _method: post }
