joboard_app_job:
    resource: "@JoboardBundle/Resources/config/routing/job.yml"
    prefix:   /app_job

joboard_homepage:
    pattern:  /
    defaults: { _controller: JoboardBundle:Job:index }

JoboardBundle_category:
    pattern:   /category/{slug}/
    defaults: { _controller: JoboardBundle:Category:show }
